@startuml
skinparam backgroundColor #EEEEEE


User -> AuthService : 发送登录请求（用户名、密码）
AuthService -> UserDB : 获取用户信息
alt
AuthService -> AuthService: 验证用户名和密码
AuthService -> User: 账号或密码不正确
end
AuthService -> AuthService: 根据用户id生成token
AuthService -> Redis: 存储token作为key，用户信息是value
AuthService -> User : 返回登录结果携带token

@enduml
