[server]
port=8003
name="syntax-train"

[db]
host="127.0.0.1"
port=9003
username='root'
password='123456'

[redis]
host="127.0.0.1"
port=26379
name='redis'

[yach]
appid='358471'
appkey='hsjskfanks'

[tracing]
endpoint = "http://localhost:14268/api/traces"
disabled=true # 开启trace支持
sampler.type="const"
sampler.param=1 # 数据全量采集

[sentry]
dsn = "https://ab906ff272a6ff85fdbaff045fbae402@o4507933316874240.ingest.us.sentry.io/4507933332930560"
env = "prod"
debug = false