[server]
port=8003
name="syntax-train"

[db]
host="127.0.0.1"
port=9003
username='root'
password='123456'

[redis]
host="127.0.0.1"
port=26379
name='redis'

[yach]
appid='358471'
appkey='hsjskfanks'

[trace]
disabled=true # 开启trace支持
sampler.type="const"
sampler.param=1 # 数据全量采集